### ISSUE TITLE
Nice submission

### ISSUE THREAD

**Issue by blat-blatnik** [markus-brln/ComputerGraphicsCompetition2021#1]
Hi again. It's nice to see your project up and running. Nice job guys.

I'm very impressed that you somehow managed to get the framework running in real time like this.

It's also super cool that you included a timeline of how your project progressed from 0 to 100 in the [documentation](https://github.com/markus-brln/ComputerGraphicsCompetition2021/tree/main/documentationProject). It's just interesting to see the process, a really nice idea :)

I hope you had fun with the project and the course!

Here's a screenshot of it running on my machine.

![image](https://user-images.githubusercontent.com/55242398/113492353-048a8b00-94d7-11eb-86e3-2ea1eeb29e15.png)

\- Boris

**Comment by markus-brln** [comment]
Thanks for the nice comment!

I didn't have to optimize anything in the assignment code though (not consciously, at least) to get around 15 fps.

Yeah the documentation will be useful in a year or so when I dig the project out after I already forgot everything that I had done.

Do you have any idea/framework as a starting point to do the computations on the GPU?

Btw, I'm jealous of your CPU now :)

**Comment by blat-blatnik** [comment]
Hmm, yea I tried replacing omp with openacc in your render loop:

```c
#pragma acc parallel loop collapse(2)
for (int y = 0; y < h; ++y)
  for (int x = 0; x < w; ++x)
    ...
```

I then compiled with -fopenacc.. but it didn't really seem to do anything. My GPU usage was basically 0 while running so I don't think it actually ran on the GPU at all. Then again I have no idea how to use openacc (even though I took the parallel computing course >.>) so maybe I'm just forgetting to do something haha.

What we did last year was just do all of the raytracing in a fragment shader. That worked reasonably well for us. We could do something like 100 objects + 30 lights rendered at 256x256 at 30 fps on a laptop gtx 1050.

Although that would basically require a full rewrite in OpenGL for you. But if you really want to do it on a GPU then that or OpenCL/CUDA are more less the only options I would look at. I wouldn't trust openacc to do anything correctly.

I think it should be possible to get almost the exact same performance on the CPU with some very optimized SIMD code and multi threading. So you could also look into that if you don't want to mess around with any GPU nonsense.

**Comment by markus-brln** [comment]
Compiling with acc gave me an error message that it couldn't parallelize the loop, I guess because it was too complicated or so.
Yeah I took parallel programming too but especially last year it wasn't very productive unfortunately...

Thanks for the suggestions though! I'll look into it after *passing* the exam :)

**Comment by blat-blatnik** [comment]
Yes, focus on that for now :D

Good luck!
